name: CI for Next.js

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_TMDB_API_KEY: ${{ secrets.NEXT_PUBLIC_TMDB_API_KEY }}
      NEXT_PUBLIC_TMDB_HOST: ${{ secrets.NEXT_PUBLIC_TMDB_HOST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Environment Variables
        run: echo "NEXT_PUBLIC_TMDB_HOST=$NEXT_PUBLIC_TMDB_HOST"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Next.js app
        run: npm run build
